jar = ../../kwalify.jar
all:
	java -classpath $(jar) kwalify.Main -lm address-book.schema.yaml
	java -classpath $(jar) kwalify.Main -lf address-book.schema.yaml address-book.yaml
#	kwalify -lm address-book.schema.yaml
#	kwalify -lf address-book.schema.yaml address-book.yaml

